export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";

export const FETCH_CONTENTS = "FETCH_CONTENTS";
export const FETCH_CONTENTS_SUCCESS = "FETCH_CONTENTS_SUCCESS";
export const FETCH_CONTENTS_FAIL = "FETCH_CONTENTS_FAIL";

export const FETCH_ADVERTISEMENTS = "FETCH_ADVERTISEMENTS";
export const FETCH_ADVERTISEMENTS_SUCCESS = "FETCH_ADVERTISEMENTS_SUCCESS";
export const FETCH_ADVERTISEMENTS_FAIL = "FETCH_ADVERTISEMENTS_FAIL";

export const FETCH_CERTIFICATE_CONTENTS = "FETCH_CERTIFICATE_CONTENTS";
export const FETCH_CERTIFICATE_CONTENTS_SUCCESS =
  "FETCH_CERTIFICATE_CONTENTS_SUCCESS";
export const FETCH_CERTIFICATE_CONTENTS_FAIL =
  "FETCH_CERTIFICATE_CONTENTS_FAIL";

export const FETCH_CERTIFICATE = "FETCH_CERTIFICATE";
export const FETCH_CERTIFICATE_SUCCESS = "FETCH_CERTIFICATE_SUCCESS";
export const FETCH_CERTIFICATE_FAIL = "FETCH_CERTIFICATE_FAIL";
