export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";

export const FETCH_CALCULATOR_CONTENT = "FETCH_CALCULATOR_CONTENT";
export const FETCH_CALCULATOR_CONTENT_SUCCESS =
  "FETCH_CALCULATOR_CONTENT_SUCCESS";
export const FETCH_CALCULATOR_CONTENT_FAIL = "FETCH_CALCULATOR_CONTENT_FAIL";

export const FETCH_COUNTRIES_CONTENT = "FETCH_COUNTRIES_CONTENT";
export const FETCH_COUNTRIES_CONTENT_SUCCESS =
  "FETCH_COUNTRIES_CONTENT_SUCCESS";
export const FETCH_COUNTRIES_CONTENT_FAIL = "FETCH_COUNTRIES_CONTENT_FAIL";

export const FETCH_CITIES_CONTENT = "FETCH_CITIES_CONTENT";
export const FETCH_CITIES_CONTENT_SUCCESS = "FETCH_CITIES_CONTENT_SUCCESS";
export const FETCH_CITIES_CONTENT_FAIL = "FETCH_CITIES_CONTENT_FAIL";

export const FETCH_WEIGHT_CONTENT = "FETCH_WEIGHT_CONTENT";
export const FETCH_WEIGHT_CONTENT_SUCCESS = "FETCH_WEIGHT_CONTENT_SUCCESS";
export const FETCH_WEIGHT_CONTENT_FAIL = "FETCH_WEIGHT_CONTENT_FAIL";

export const FETCH_UNITS_OF_LENGTH_CONTENT = "FETCH_UNITS_OF_LENGTH_CONTENT";
export const FETCH_UNITS_OF_LENGTH_CONTENT_SUCCESS =
  "FETCH_UNITS_OF_LENGTH_CONTENT_SUCCESS";
export const FETCH_UNITS_OF_LENGTH_CONTENT_FAIL =
  "FETCH_UNITS_OF_LENGTH_CONTENT_FAIL";

export const FETCH_PRODUCT_TYPES_CONTENT = "FETCH_PRODUCT_TYPES_CONTENT";
export const FETCH_PRODUCT_TYPES_CONTENT_SUCCESS =
  "FETCH_PRODUCT_TYPES_CONTENT_SUCCESS";
export const FETCH_PRODUCT_TYPES_CONTENT_FAIL =
  "FETCH_PRODUCT_TYPES_CONTENT_FAIL";

export const FETCH_ADVERTISEMENTS = "FETCH_ADVERTISEMENTS";
export const FETCH_ADVERTISEMENTS_SUCCESS = "FETCH_ADVERTISEMENTS_SUCCESS";
export const FETCH_ADVERTISEMENTS_FAIL = "FETCH_ADVERTISEMENTS_FAIL";

export const FETCH_HOW_IT_WORKS_CONTENT = "FETCH_HOW_IT_WORKS_CONTENT";
export const FETCH_HOW_IT_WORKS_CONTENT_SUCCESS =
  "FETCH_HOW_IT_WORKS_CONTENT_SUCCESS";
export const FETCH_HOW_IT_WORKS_CONTENT_FAIL =
  "FETCH_HOW_IT_WORKS_CONTENT_FAIL";

export const FETCH_HOW_IT_WORKS_CARD_CONTENT =
  "FETCH_HOW_IT_WORKS_CARD_CONTENT";
export const FETCH_HOW_IT_WORKS_CARD_CONTENT_SUCCESS =
  "FETCH_HOW_IT_WORKS_CARD_CONTENT_SUCCESS";
export const FETCH_HOW_IT_WORKS_CARD_CONTENT_FAIL =
  "FETCH_HOW_IT_WORKS_CARD_CONTENT_FAIL";

export const FETCH_CERTIFICATE_CONTENTS = "FETCH_CERTIFICATE_CONTENTS";
export const FETCH_CERTIFICATE_CONTENTS_SUCCESS =
  "FETCH_CERTIFICATE_CONTENTS_SUCCESS";
export const FETCH_CERTIFICATE_CONTENTS_FAIL =
  "FETCH_CERTIFICATE_CONTENTS_FAIL";

export const FETCH_CERTIFICATE = "FETCH_CERTIFICATE";
export const FETCH_CERTIFICATE_SUCCESS = "FETCH_CERTIFICATE_SUCCESS";
export const FETCH_CERTIFICATE_FAIL = "FETCH_CERTIFICATE_FAIL";

export const FETCH_ADVERTISEMENT_TITLE = "FETCH_ADVERTISEMENT_TITLE";
export const FETCH_ADVERTISEMENT_TITLE_SUCCESS =
  "FETCH_ADVERTISEMENT_TITLE_SUCCESS";
export const FETCH_ADVERTISEMENT_TITLE_FAIL = "FETCH_ADVERTISEMENT_TITLE_FAIL";

export const FETCH_RECOMMENDED_SHOPS = "FETCH_RECOMMENDED_SHOPS";
export const FETCH_RECOMMENDED_SHOPS_SUCCESS =
  "FETCH_RECOMMENDED_SHOPS_SUCCESS";
export const FETCH_RECOMMENDED_SHOPS_FAIL = "FETCH_RECOMMENDED_SHOPS_FAIL";

export const FETCH_SOCIAL_MEDIAS = "FETCH_SOCIAL_MEDIAS";
export const FETCH_SOCIAL_MEDIAS_SUCCESS = "FETCH_SOCIAL_MEDIAS_SUCCESS";
export const FETCH_SOCIAL_MEDIAS_FAIL = "FETCH_SOCIAL_MEDIAS_FAIL";

export const FETCH_CONTACT = "FETCH_CONTACT";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_FAIL = "FETCH_CONTACT_FAIL";

export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_FAIL = "FETCH_CONTACTS_FAIL";

export const FETCH_CONTACT_CONTENT = "FETCH_CONTACT_CONTENT";
export const FETCH_CONTACT_CONTENT_SUCCESS = "FETCH_CONTACT_CONTENT_SUCCESS";
export const FETCH_CONTACT_CONTENT_FAIL = "FETCH_CONTACT_CONTENT_FAIL";

export const FETCH_SHOPS = "FETCH_SHOPS";
export const FETCH_SHOPS_SUCCESS = "FETCH_SHOPS_SUCCESS";
export const FETCH_SHOPS_FAIL = "FETCH_SHOPS_FAIL";

export const GET_SHOPS_COUNT = "FETCH_SHOPS";
export const GET_SHOPS_COUNT_SUCCESS = "GET_SHOPS_COUNT_SUCCESS";
export const GET_SHOPS_COUNT_FAIL = "GET_SHOPS_COUNT_FAIL";

export const FETCH_SHOP_CONTENT = "FETCH_SHOP_CONTENT";
export const FETCH_SHOP_CONTENT_SUCCESS = "FETCH_SHOP_CONTENT_SUCCESS";
export const FETCH_SHOP_CONTENT_FAIL = "FETCH_SHOP_CONTENT_FAIL";

export const FETCH_COUNTRY_CONTENT = "FETCH_COUNTRY_CONTENT";
export const FETCH_COUNTRY_CONTENT_SUCCESS = "FETCH_COUNTRY_CONTENT_SUCCESS";
export const FETCH_COUNTRY_CONTENT_FAIL = "FETCH_COUNTRY_CONTENT_FAIL";

export const GET_EXCAHGE_RATE = "GET_EXCAHGE_RATE";
export const GET_EXCAHGE_RATE_SUCCESS = "GET_EXCAHGE_RATE_SUCCESS";
export const GET_EXCAHGE_RATE_FAIL = "GET_EXCAHGE_RATE_FAIL";

export const FETCH_CALCULATOR_INFORMATION_CONTENT =
  "FETCH_CALCULATOR_INFORMATION_CONTENT";
export const FETCH_CALCULATOR_INFORMATION_CONTENT_SUCCESS =
  "FETCH_CALCULATOR_INFORMATION_CONTENT_SUCCESS";
export const FETCH_CALCULATOR_INFORMATION_CONTENT_FAIL =
  "FETCH_CALCULATOR_INFORMATION_CONTENT_FAIL";

export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAIL = "FETCH_CURRENCY_FAIL";

export const FETCH_CALCULATOR_PAGE_CONTENT = "FETCH_CALCULATOR_PAGE_CONTENT";
export const FETCH_CALCULATOR_PAGE_CONTENT_SUCCESS =
  "FETCH_CALCULATOR_PAGE_CONTENT_SUCCESS";
export const FETCH_CALCULATOR_PAGE_CONTENT_FAIL =
  "FETCH_CALCULATOR_PAGE_CONTENT_FAIL";

export const FETCH_RULES = "FETCH_RULES";
export const FETCH_RULES_SUCCESS = "FETCH_RULES_SUCCESS";
export const FETCH_RULES_FAIL = "FETCH_RULES_FAIL";

export const FETCH_RULES_CONTENT = "FETCH_RULES_CONTENT";
export const FETCH_RULES_CONTENT_SUCCESS = "FETCH_RULES_CONTENT_SUCCESS";
export const FETCH_RULES_CONTENT_FAIL = "FETCH_RULES_CONTENT_FAIL";
