export const FETCH_AUXILIARY_SECTIONS = "FETCH_AUXILIARY_SECTIONS";
export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_AUTHENTICATIONS = "FETCH_AUTHENTICATIONS";
export const FETCH_SECTIONS = "FETCH_SECTIONS";
export const FETCH_ORDER = "FETCH_ORDER";
