export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";

export const FETCH_CALCULATOR_CONTENT = "FETCH_CALCULATOR_CONTENT";
export const FETCH_CALCULATOR_CONTENT_SUCCESS =
  "FETCH_CALCULATOR_CONTENT_SUCCESS";
export const FETCH_CALCULATOR_CONTENT_FAIL = "FETCH_CALCULATOR_CONTENT_FAIL";

export const FETCH_COUNTRIES_CONTENT = "FETCH_COUNTRIES_CONTENT";
export const FETCH_COUNTRIES_CONTENT_SUCCESS =
  "FETCH_COUNTRIES_CONTENT_SUCCESS";
export const FETCH_COUNTRIES_CONTENT_FAIL = "FETCH_COUNTRIES_CONTENT_FAIL";

export const FETCH_CITIES_CONTENT = "FETCH_CITIES_CONTENT";
export const FETCH_CITIES_CONTENT_SUCCESS = "FETCH_CITIES_CONTENT_SUCCESS";
export const FETCH_CITIES_CONTENT_FAIL = "FETCH_CITIES_CONTENT_FAIL";

export const FETCH_PRODUCT_TYPES_CONTENT = "FETCH_PRODUCT_TYPES_CONTENT";
export const FETCH_PRODUCT_TYPES_CONTENT_SUCCESS =
  "FETCH_PRODUCT_TYPES_CONTENT_SUCCESS";
export const FETCH_PRODUCT_TYPES_CONTENT_FAIL =
  "FETCH_PRODUCT_TYPES_CONTENT_FAIL";

export const FETCH_ADVERTISEMENTS = "FETCH_ADVERTISEMENTS";
export const FETCH_ADVERTISEMENTS_SUCCESS = "FETCH_ADVERTISEMENTS_SUCCESS";
export const FETCH_ADVERTISEMENTS_FAIL = "FETCH_ADVERTISEMENTS_FAIL";

export const FETCH_SHOPS = "FETCH_SHOPS";
export const FETCH_SHOPS_SUCCESS = "FETCH_SHOPS_SUCCESS";
export const FETCH_SHOPS_FAIL = "FETCH_SHOPS_FAIL";

export const GET_SHOPS_COUNT = "FETCH_SHOPS";
export const GET_SHOPS_COUNT_SUCCESS = "GET_SHOPS_COUNT_SUCCESS";
export const GET_SHOPS_COUNT_FAIL = "GET_SHOPS_COUNT_FAIL";

export const FETCH_SHOP_CONTENT = "FETCH_SHOP_CONTENT";
export const FETCH_SHOP_CONTENT_SUCCESS = "FETCH_SHOP_CONTENT_SUCCESS";
export const FETCH_SHOP_CONTENT_FAIL = "FETCH_SHOP_CONTENT_FAIL";

export const FETCH_COUNTRY_CONTENT = "FETCH_COUNTRY_CONTENT";
export const FETCH_COUNTRY_CONTENT_SUCCESS = "FETCH_COUNTRY_CONTENT_SUCCESS";
export const FETCH_COUNTRY_CONTENT_FAIL = "FETCH_COUNTRY_CONTENT_FAIL";

export const GET_EXCAHGE_RATE = "GET_EXCAHGE_RATE";
export const GET_EXCAHGE_RATE_SUCCESS = "GET_EXCAHGE_RATE_SUCCESS";
export const GET_EXCAHGE_RATE_FAIL = "GET_EXCAHGE_RATE_FAIL";

export const FETCH_CALCULATOR_INFORMATION_CONTENT =
  "FETCH_CALCULATOR_INFORMATION_CONTENT";
export const FETCH_CALCULATOR_INFORMATION_CONTENT_SUCCESS =
  "FETCH_CALCULATOR_INFORMATION_CONTENT_SUCCESS";
export const FETCH_CALCULATOR_INFORMATION_CONTENT_FAIL =
  "FETCH_CALCULATOR_INFORMATION_CONTENT_FAIL";

export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAIL = "FETCH_CURRENCY_FAIL";

export const FETCH_CALCULATOR_PAGE_CONTENT = "FETCH_CALCULATOR_PAGE_CONTENT";
export const FETCH_CALCULATOR_PAGE_CONTENT_SUCCESS =
  "FETCH_CALCULATOR_PAGE_CONTENT_SUCCESS";
export const FETCH_CALCULATOR_PAGE_CONTENT_FAIL =
  "FETCH_CALCULATOR_PAGE_CONTENT_FAIL";

export const FETCH_GENDERS = "FETCH_GENDERS";
export const FETCH_GENDERS_SUCCESS = "FETCH_GENDERS_SUCCESS";
export const FETCH_GENDERS_FAIL = "FETCH_GENDERS_FAIL";

export const SET_USER = "SET_USER";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAIL = "SET_USER_FAIL";

export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";

export const SET_PRICE = "SET_PRICE";
